<?php // @codingStandardsIgnoreFile ?>
<div class='dagpay'>
	<div class='errors'>
		<?php if ($block->getMessages()) : ?>
            <?php foreach ($block->getMessages() as $message) : ?>
                <div class='alert alert-danger'><p style='color:red'><?= $block->escapeHtml($message) ?></p></div>
            <?php endforeach; ?>
            <?php if ($block->getShowPhoneBox()) : ?>
                <form method='post'>
                    <label>Telephone</label><input type='text' name='telephone' value='<?php echo $block->escapeHtml($block->getTelephone()) ?>' />
                    <div><input type='submit' class='btn btn-primary' value='UPDATE TELEPHONE'></div>
                </form>
            <?php endif; ?>
        <?php else : ?>
            <div style="width:200px;margin:auto;margin-top:20px">
            <img style="width:100%" src="<?php echo $block->escapeXssInUrl($block->getViewFileUrl('Dagcoin_PaymentGateway::images/spinner.gif')); ?>">
            <center>Redirecting you to DagPay</center>
            </div>
            <form name="dagpaypaymentredirect" action='<?= $block->escapeHtml($block->getAction()) ?>'>
                <input type='hidden' name='embed' value='form'>
            </form>
            <script type="text/x-magento-init"></script>
            <script>
                document.dagpaypaymentredirect.submit();
            </script>
        <?php endif; ?>
    </div>
</div>
